Improve flex error targets.

diff --git a/src/df1b2-separable/GNUmakefile b/src/df1b2-separable/GNUmakefile
--- a/src/df1b2-separable/GNUmakefile
+++ b/src/df1b2-separable/GNUmakefile
@@ -17,10 +17,12 @@ $(DIST)/bin/tpl2rem: tpl2rem.c
 	$(CC) $(CFLAGS) -o $@ $<
 
 tpl2rem.c: lex.yy.c
-	if [ "`cat $^ | wc -l`" -ne 0 ]; then sed -f sedflex $^ > $@; else rm -vf $@; fi
+	rm -vf $@
+	if [ "`cat $^ | wc -l`" -ne 0 ]; then sed -f sedflex $^ > $@; fi
 	@#if [ ! -f $@ ]; then cp -vf tpl2rem-unixflex.c $@; fi
 
 lex.yy.c: tpl2rem.lex
-	if [ `command -v flex` ]; then flex -v -w $^; else rm -vf $@; fi
-	if [ ! -f $@ ]; then echo "Error: Unable to find flex."; exit 2; fi
+	rm -vf $@
+	if [ -z "`command -v flex`" ]; then echo "Error: Unable to find flex."; exit 1; fi
+	flex -v -w $^
 endif
