Exit if flex not installed.

diff --git a/src/df1b2-separable/GNUmakefile b/src/df1b2-separable/GNUmakefile
--- a/src/df1b2-separable/GNUmakefile
+++ b/src/df1b2-separable/GNUmakefile
@@ -22,5 +22,5 @@ tpl2rem.c: lex.yy.c
 
 lex.yy.c: tpl2rem.lex
 	if [ `command -v flex` ]; then flex -v -w $^; else rm -vf $@; fi
-	if [ ! -f $@ ]; then touch $@; fi
+	if [ ! -f $@ ]; then echo "Error: Unable to find flex."; exit 2; fi
 endif
diff --git a/src/nh99/GNUmakefile b/src/nh99/GNUmakefile
--- a/src/nh99/GNUmakefile
+++ b/src/nh99/GNUmakefile
@@ -24,5 +24,5 @@ tpl2cpp.c: lex.yy.c
 	@#if [ ! -f $@ ]; then cp -vf tpl2cpp-unixflex.c $@; fi
 lex.yy.c: tpl2cpp.lex
 	if [ `command -v flex` ]; then flex -v -w $^; else rm -vf $@; fi
-	if [ ! -f $@ ]; then touch $@; fi
+	if [ ! -f $@ ]; then echo "Error: Unable to find flex."; exit 2; fi
 endif
