Clean up build files for tpl2cpp and tpl2rem.

diff --git a/src/df1b2-separable/GNUmakefile b/src/df1b2-separable/GNUmakefile
--- a/src/df1b2-separable/GNUmakefile
+++ b/src/df1b2-separable/GNUmakefile
@@ -9,19 +9,17 @@ endif
 	$(CC) $(CFLAGS) -o $@ $<
 
 tpl2rem.c: lex.yy.c
-ifeq ($(OS),Windows_NT)
-	sed -f sedflex lex.yy.c > $@
-else
+ifneq ($(OS),Windows_NT)
 	rm -vf $@
-	if [ "`cat $^ | wc -l`" -ne 0 ]; then sed -f sedflex $^ > $@; fi
+	if [ "`cat $^ | wc -l`" -eq 0 ]; then echo "Error: lex.yy.c is empty."; exit 1; fi
 	@#if [ ! -f $@ ]; then cp -vf tpl2rem-unixflex.c $@; fi
 endif
+	sed -f sedflex $^ > $@
 
 lex.yy.c: tpl2rem.lex
-ifeq ($(OS)_$(TERM),Windows_NT_)
+ifneq ($(OS),Windows_NT)
 	flex -w tpl2rem.lex
-else
 	rm -vf $@
-	if [ -z "`command -v flex`" ]; then echo "Error: Unable to find flex."; exit 1; fi
-	flex -v -w $^
+	@if [ -z "`command -v flex`" ]; then echo "Error: Unable to find flex."; exit 1; fi
 endif
+	flex -v -w $^
diff --git a/src/nh99/GNUmakefile b/src/nh99/GNUmakefile
--- a/src/nh99/GNUmakefile
+++ b/src/nh99/GNUmakefile
@@ -1,4 +1,5 @@
 ifeq ($(OS),Windows_NT)
+PATH:=$(PATH):..\..\utilities
 bins: $(DIST)\bin\tpl2cpp.exe
 $(DIST)\bin\tpl2cpp.exe: tpl2cpp.c
 else
@@ -11,20 +12,17 @@ else
 	$(CC) $(CFLAGS) -Wno-format -o $@ $<
 endif
 
-ifeq ($(OS)_$(TERM),Windows_NT_)
 tpl2cpp.c: lex.yy.c
-	..\..\utilities\sed -f sedflex lex.yy.c > $@
-
-lex.yy.c: tpl2cpp.lex
-	..\..\utilities\flex tpl2cpp.lex
-else
-tpl2cpp.c: lex.yy.c
+ifneq ($(OS),Windows_NT)
 	rm -vf $@
-	if [ "`cat $^ | wc -l`" -ne 0 ]; then sed -f sedflex $^ > $@; fi
+	if [ "`cat $^ | wc -l`" -eq 0 ]; then echo "Error: lex.yy.c is empty."; exit 1; fi
 	@#if [ ! -f $@ ]; then cp -vf tpl2cpp-unixflex.c $@; fi
+endif
+	sed -f sedflex lex.yy.c > $@
 
 lex.yy.c: tpl2cpp.lex
+ifneq ($(OS),Windows_NT)
 	rm -vf $@
 	if [ -z "`command -v flex`" ]; then echo "Error: Unable to find flex."; exit 1; fi
-	flex -v -w $^
 endif
+	flex -v -w $^
